algolia:
  appid: V6SCF4H8H6
  index: churches_dev
  key: b294ae630f797e9a055c700753b6f4f4
mombasa:
  rate: 2.0
mpesa:
  appkey: At2WigukYMYmKS5FAamPmFPpidWUxGUM
  appsecret: wA2LqmDDHVrQf4I3
  authurl: https://api.safaricom.co.ke/oauth/v1/generate?grant_type=client_credentials
  callbackurl: http://msadaka-server.us-east-1.elasticbeanstalk.com/api/v1/mpesa-call-back
  endpoint: https://api.safaricom.co.ke/mpesa/stkpush/v1/processrequest
  passkey: 45b8d79eba4a027bd8d54ac52e9c18950a54d04ed681f5de00d02364c1027edf
  shortcode: 333306
nairobi:
  rate: 1.0
sms:
  apikey: 211cbffc266102e114aae4bdebbcae84bf608853d24cb1d2617aa2399ef3958d
  send: false
  username: kespay
spring:
  datasource:
    url: jdbc:h2:~/tmp/db/msadaka;DB_CLOSE_DELAY=-1
    username: sa
    password:
    testWhileIdle: true
    validationQuery: SELECT 1
  h2:
    console:
      enabled: true
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
