version: 2
jobs:
  build:
    working_directory: ~/msadaka-server
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - run:
          name: Run Tests and check coverage
          command: ./gradlew check

      - run: ./gradlew build

  build_docker:
    working_directory: ~/msadaka-server
    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build application Docker image
          command: |
            docker build -t ckeidev/msadaka-server:$CIRCLE_SHA1 .
      - run:
          name: Save application Docker image
          command: |
            mkdir /tmp/workspace
            docker save -o /tmp/workspace/image.tar ckeidev/msadaka-server:$CIRCLE_SHA1
      - persist_to_workspace:
          # Must be an absolute path, or relative path from working_directory. This is a directory on the container which is
          # taken to be the root directory of the workspace.
          root: /tmp

          paths:
            - workspace

  push_latest:
    working_directory: ~/msadaka-server
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load application Docker image
          command: |
            docker load --input /tmp/workspace/image.tar
      - run:
          name: Tag docker image
          command: |
            docker tag ckeidev/msadaka-server:$CIRCLE_SHA1 ckeidev/msadaka-server:latest
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ckeidev/msadaka-server:latest


  push_production:
    working_directory: ~/msadaka-server
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load application Docker image
          command: |
            docker load --input /tmp/workspace/image.tar
      - run:
          name: Tag docker image
          command: |
            docker tag ckeidev/msadaka-server:$CIRCLE_SHA1 ckeidev/msadaka-server:production
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ckeidev/msadaka-server:production

  push_tagged:
    working_directory: ~/msadaka-server
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp
      - run:
          name: Load application Docker image
          command: |
            docker load --input /tmp/workspace/image.tar
      - run:
          name: Tag docker image
          command: |
            docker tag ckeidev/msadaka-server:$CIRCLE_SHA1 ckeidev/msadaka-server:$CIRCLE_TAG
      - run:
          name: Push application Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker push ckeidev/msadaka-server:$CIRCLE_TAG

workflows:
  version: 2
  build_and_push:
    jobs:
      - build
      - build_docker:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - develop
                - master
          requires:
            - build
      - push_latest:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - develop
          requires:
            - build_docker
      - push_production:
          filters:
            tags:
              only: /^v.*/
            branches:
              only:
                - master
          requires:
            - build_docker
      - push_tagged:
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
          requires:
            - build_docker